-- ============================================================================
-- CISUR — correr los smoke tests de seguridad
--
-- Verifica que alguien con la publishable key en mano (o sea: cualquiera,
-- porque viaja en el bundle del navegador) no pueda leer ni escribir lo que no
-- le toca. Son 58 pruebas sobre los dos candados del proyecto:
--
--   · privilegios de tabla → si la operación está permitida siquiera
--   · RLS                  → sobre qué filas
--
-- ANTES, UNA SOLA VEZ
--   Correr `instalar_smoke_tests.sql`, que deja la suite instalada.
--
-- DESPUÉS, CADA VEZ
--   Pegar esta línea en el SQL Editor y darle Run.
--
-- La última fila tiene que decir "TODO OK — 58 pruebas pasaron". Si alguna
-- falla, la columna `detalle` explica qué pasó.
--
-- La suite prepara sus datos, prueba y limpia dentro de la misma llamada: no
-- deja nada en la base y se puede correr las veces que haga falta.
--
-- Correlo cada vez que toques una policy, un grant o un trigger.
-- ============================================================================

select * from public.cisur_smoke_tests();
